spring:
  application:
    name: auth
  jpa:
    hibernate:
      ddl-auto: validate

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/chat_server?serverTimezone=UTC&characterEncoding=UTF-8
    dbcp2:
      max-idle: 5
      min-idle: 5
      max-total: 5
      test-on-borrow: true
      test-on-return: true
      test-on-create: true
  profiles:
    group:
      dev:
        - api

      prod:
        - api
    active: dev

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - profile
              - email
            redirect-uri: "http://localhost:9090/login/oauth2/code/{registrationId}"

          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8080/a/login/oauth2/code/{registrationId}"
            scope:
              - profile_nickname
              - profile_image
            client-name: Kakao

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id


server:
  port: 9090
  forward-headers-strategy: framework

app:
  front-url: http://localhost:8080
  cookie:
    secure: false

logging:
  level:
    root: info
    com.chat_server: debug
    org.springframework: info
    org.springframework.web.filter: debug
    org.hibernate.SQL: DEBUG
    # SQL 로그 보기 (선택)
    io.netty: WARN
    reactor.netty: WARN
    org.apache.http: WARN

  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

redis:
  key:
    prefix:
      refresh-token: "refresh:"