auth:
  token:
    access-token:
      expiration: 1800
    refresh-token:
      expiration: 10000
    key:
      public-path: file:/etc/auth
      private-path: file:/etc/auth
spring:
  datasource:
    username: nhn_academy_150
    password: jJ6oejil!