spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - profile
              - email
            redirect-uri: "http://localhost:9090/login/oauth2/code/{registrationId}"

          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8080/a/login/oauth2/code/{registrationId}"
            scope:
              - profile_nickname
              - profile_image
            client-name: Kakao

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id


auth:
  token:
    access-token:
      expiration: 10000
      iss: chat
    refresh-token:
      iss: chat
      expiration: 10000
  key:
    public-path: classpath:rsa/dev/login_public_key.pem
    private-path: classpath:rsa/dev/login_private_key.pem

